// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: internal/pb/barrage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 操作类型定义
type OpType int32

const (
	// 未知操作
	OpType_OP_UNKNOWN OpType = 0
	// 加入房间
	OpType_OP_JOIN_ROOM OpType = 1
	// 客户端发送聊天消息
	OpType_OP_CHAT OpType = 2
	// 心跳消息
	OpType_OP_HEARTBEAT OpType = 3
	// 服务端广播消息
	OpType_OP_BROADCAST OpType = 4
	// 服务端返回错误
	OpType_OP_ERROR OpType = 5
	// 系统消息 / 公告
	OpType_OP_SYSTEM OpType = 6
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_UNKNOWN",
		1: "OP_JOIN_ROOM",
		2: "OP_CHAT",
		3: "OP_HEARTBEAT",
		4: "OP_BROADCAST",
		5: "OP_ERROR",
		6: "OP_SYSTEM",
	}
	OpType_value = map[string]int32{
		"OP_UNKNOWN":   0,
		"OP_JOIN_ROOM": 1,
		"OP_CHAT":      2,
		"OP_HEARTBEAT": 3,
		"OP_BROADCAST": 4,
		"OP_ERROR":     5,
		"OP_SYSTEM":    6,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_barrage_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_internal_pb_barrage_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{0}
}

// 系统下发的公告或事件通知
type SystemMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息内容
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// 消息类型（如 1: 公告，2: 房间通知，3: 系统事件等）
	Type          int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMsg) Reset() {
	*x = SystemMsg{}
	mi := &file_internal_pb_barrage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMsg) ProtoMessage() {}

func (x *SystemMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMsg.ProtoReflect.Descriptor instead.
func (*SystemMsg) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SystemMsg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 服务端下发的错误消息
type ErrorMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误信息描述
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	mi := &file_internal_pb_barrage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorMsg) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// WebSocket 二进制帧中的统一外层协议
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前消息操作类型
	Op OpType `protobuf:"varint,1,opt,name=op,proto3,enum=barrage.OpType" json:"op,omitempty"`
	// 房间 ID
	RoomId int64 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 用户 ID
	UserId int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 具体业务负载，里面再嵌套不同消息体
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// 毫秒时间戳
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_internal_pb_barrage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{2}
}

func (x *Frame) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_UNKNOWN
}

func (x *Frame) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Frame) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 加入房间请求
type JoinRoomReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 房间 ID
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 用户 ID
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 是否为付费用户
	IsPremium bool `protobuf:"varint,3,opt,name=is_premium,json=isPremium,proto3" json:"is_premium,omitempty"`
	// 鉴权 token
	Token         string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	mi := &file_internal_pb_barrage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoomReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinRoomReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *JoinRoomReq) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

func (x *JoinRoomReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 聊天消息体
type ChatMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 弹幕文本内容
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	mi := &file_internal_pb_barrage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 广播消息体
type BroadcastMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 房间 ID
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 发送者用户 ID
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 发送内容
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// 毫秒时间戳
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMsg) Reset() {
	*x = BroadcastMsg{}
	mi := &file_internal_pb_barrage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMsg) ProtoMessage() {}

func (x *BroadcastMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMsg.ProtoReflect.Descriptor instead.
func (*BroadcastMsg) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastMsg) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *BroadcastMsg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BroadcastMsg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *BroadcastMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Kafka 广播链路中的统一消息体
type BroadcastEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息类型：0=弹幕(不重试), 1=礼物(重试), 2=道具(重试), 3=彩色弹幕(重试)
	MsgType int32 `protobuf:"varint,8,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	// 幂等key，用于特殊消息去重 (格式: userId_roomId_timestamp_random)
	IdempotencyKey string `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// 房间 ID
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 发送者用户 ID
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 发送者连接 ID
	SenderConnId string `protobuf:"bytes,3,opt,name=sender_conn_id,json=senderConnId,proto3" json:"sender_conn_id,omitempty"`
	// 是否为付费用户
	IsPremium bool `protobuf:"varint,4,opt,name=is_premium,json=isPremium,proto3" json:"is_premium,omitempty"`
	// 最终可直接下发给客户端的 protobuf 二进制负载
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// 毫秒时间戳
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 视频时间戳 (毫秒) - 弹幕对应的视频时刻，用于弹幕和视频同步
	VideoTs       int64 `protobuf:"varint,7,opt,name=video_ts,json=videoTs,proto3" json:"video_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastEnvelope) Reset() {
	*x = BroadcastEnvelope{}
	mi := &file_internal_pb_barrage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastEnvelope) ProtoMessage() {}

func (x *BroadcastEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastEnvelope.ProtoReflect.Descriptor instead.
func (*BroadcastEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{6}
}

func (x *BroadcastEnvelope) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *BroadcastEnvelope) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BroadcastEnvelope) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *BroadcastEnvelope) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BroadcastEnvelope) GetSenderConnId() string {
	if x != nil {
		return x.SenderConnId
	}
	return ""
}

func (x *BroadcastEnvelope) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

func (x *BroadcastEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BroadcastEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BroadcastEnvelope) GetVideoTs() int64 {
	if x != nil {
		return x.VideoTs
	}
	return 0
}

// 视频时间戳更新 (用于视频同步)
type VideoTSUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 房间 ID
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 当前视频时间戳 (毫秒)
	VideoTs int64 `protobuf:"varint,2,opt,name=video_ts,json=videoTs,proto3" json:"video_ts,omitempty"`
	// 墙钟发送时间 (毫秒)
	SentAt        int64 `protobuf:"varint,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoTSUpdate) Reset() {
	*x = VideoTSUpdate{}
	mi := &file_internal_pb_barrage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTSUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTSUpdate) ProtoMessage() {}

func (x *VideoTSUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTSUpdate.ProtoReflect.Descriptor instead.
func (*VideoTSUpdate) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{7}
}

func (x *VideoTSUpdate) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *VideoTSUpdate) GetVideoTs() int64 {
	if x != nil {
		return x.VideoTs
	}
	return 0
}

func (x *VideoTSUpdate) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

// 心跳消息
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端时间戳
	ClientTs      int64 `protobuf:"varint,1,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_pb_barrage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_barrage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_pb_barrage_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetClientTs() int64 {
	if x != nil {
		return x.ClientTs
	}
	return 0
}

var File_internal_pb_barrage_proto protoreflect.FileDescriptor

const file_internal_pb_barrage_proto_rawDesc = "" +
	"\n" +
	"\x19internal/pb/barrage.proto\x12\abarrage\"9\n" +
	"\tSystemMsg\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\"8\n" +
	"\bErrorMsg\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x92\x01\n" +
	"\x05Frame\x12\x1f\n" +
	"\x02op\x18\x01 \x01(\x0e2\x0f.barrage.OpTypeR\x02op\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"t\n" +
	"\vJoinRoomReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"is_premium\x18\x03 \x01(\bR\tisPremium\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"#\n" +
	"\aChatMsg\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"r\n" +
	"\fBroadcastMsg\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xa1\x02\n" +
	"\x11BroadcastEnvelope\x12\x19\n" +
	"\bmsg_type\x18\b \x01(\x05R\amsgType\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12$\n" +
	"\x0esender_conn_id\x18\x03 \x01(\tR\fsenderConnId\x12\x1d\n" +
	"\n" +
	"is_premium\x18\x04 \x01(\bR\tisPremium\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bvideo_ts\x18\a \x01(\x03R\avideoTs\"\\\n" +
	"\rVideoTSUpdate\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x19\n" +
	"\bvideo_ts\x18\x02 \x01(\x03R\avideoTs\x12\x17\n" +
	"\asent_at\x18\x03 \x01(\x03R\x06sentAt\"(\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tclient_ts\x18\x01 \x01(\x03R\bclientTs*x\n" +
	"\x06OpType\x12\x0e\n" +
	"\n" +
	"OP_UNKNOWN\x10\x00\x12\x10\n" +
	"\fOP_JOIN_ROOM\x10\x01\x12\v\n" +
	"\aOP_CHAT\x10\x02\x12\x10\n" +
	"\fOP_HEARTBEAT\x10\x03\x12\x10\n" +
	"\fOP_BROADCAST\x10\x04\x12\f\n" +
	"\bOP_ERROR\x10\x05\x12\r\n" +
	"\tOP_SYSTEM\x10\x06B\x15Z\x13barrage/internal/pbb\x06proto3"

var (
	file_internal_pb_barrage_proto_rawDescOnce sync.Once
	file_internal_pb_barrage_proto_rawDescData []byte
)

func file_internal_pb_barrage_proto_rawDescGZIP() []byte {
	file_internal_pb_barrage_proto_rawDescOnce.Do(func() {
		file_internal_pb_barrage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_barrage_proto_rawDesc), len(file_internal_pb_barrage_proto_rawDesc)))
	})
	return file_internal_pb_barrage_proto_rawDescData
}

var file_internal_pb_barrage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_barrage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_pb_barrage_proto_goTypes = []any{
	(OpType)(0),               // 0: barrage.OpType
	(*SystemMsg)(nil),         // 1: barrage.SystemMsg
	(*ErrorMsg)(nil),          // 2: barrage.ErrorMsg
	(*Frame)(nil),             // 3: barrage.Frame
	(*JoinRoomReq)(nil),       // 4: barrage.JoinRoomReq
	(*ChatMsg)(nil),           // 5: barrage.ChatMsg
	(*BroadcastMsg)(nil),      // 6: barrage.BroadcastMsg
	(*BroadcastEnvelope)(nil), // 7: barrage.BroadcastEnvelope
	(*VideoTSUpdate)(nil),     // 8: barrage.VideoTSUpdate
	(*Heartbeat)(nil),         // 9: barrage.Heartbeat
}
var file_internal_pb_barrage_proto_depIdxs = []int32{
	0, // 0: barrage.Frame.op:type_name -> barrage.OpType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_barrage_proto_init() }
func file_internal_pb_barrage_proto_init() {
	if File_internal_pb_barrage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_barrage_proto_rawDesc), len(file_internal_pb_barrage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_barrage_proto_goTypes,
		DependencyIndexes: file_internal_pb_barrage_proto_depIdxs,
		EnumInfos:         file_internal_pb_barrage_proto_enumTypes,
		MessageInfos:      file_internal_pb_barrage_proto_msgTypes,
	}.Build()
	File_internal_pb_barrage_proto = out.File
	file_internal_pb_barrage_proto_goTypes = nil
	file_internal_pb_barrage_proto_depIdxs = nil
}
